pattern_name: context_by_environmental_process

pattern_iri: https://github.com/Active-Animals/Ontology/patterns/context_by_environmental_process

description: >-
  This pattern captures context behaviours which are best differentiated by the environmental processes which they incorporate.

  Examples:
  - basking: resting that involves the 'insolation' process

contributors:
  - https://orcid.org/0000-0002-6601-2165
  - https://orcid.org/0000-0002-4277-2151

classes:
  context_behaviour: ACTAN:0000751
  environmental_system_process: ENVO:02500000

relations:
  has_part: BFO:0000051
  
vars:
  context: "'context_behaviour'"
  environmental_process: "'environmental_system_process'"

name:
  text: "%s"
  vars:
    - context

def:
  text: "%s that involves %s."
  vars:
    - context
    - environmental_process

equivalentTo:
  text: "%s and 'has_part' some %s"
  vars:
    - context
    - environmental_process
